name: Create Release

on:
  push:
    branches:
      - github-actions-warnings

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Print Working Directory
      run: pwd

    - name: Install dependencies
      run: npm ci

    - name: Run Unit Tests
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        xvfb-run -a npm test

    - name: Build Extension
      run: npm run build

    - name: Get Version
      id: get_version
      run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

    - name: Package Extension
      run: npx vsce package --out pretty-json-preview-${{ steps.get_version.outputs.VERSION }}.vsix

    - name: Get Package Name
      id: package-name
      run: echo "name=$(node -p "require('./package.json').name")" >> $GITHUB_OUTPUT

    - name: Publish to Visual Studio Marketplace
      run: npx vsce publish --packagePath ${{ github.workspace }}/pretty-json-preview-${{ steps.get_version.outputs.VERSION }}.vsix -p ${{ secrets.VSCE_TOKEN }}

    - name: Create Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.get_version.outputs.VERSION }}
        name: Release ${{ steps.get_version.outputs.VERSION }}
        body_path: CHANGELOG.md
        draft: false
        prerelease: false
        files: ${{ github.workspace }}/pretty-json-preview-${{ steps.get_version.outputs.VERSION }}.vsix
